FROM golang:1.18 AS build

ARG TARGETARCH
ARG TARGETOS

WORKDIR /app

COPY go.mod /app/
COPY go.sum /app/

RUN go mod download

COPY . /app/

RUN GOOS=linux GOARCH=${BUILDPLATFORM} GO111MODULE=on CGO_ENABLED=0 go build -mod vendor -o me-snor3-parser ./cmd/

FROM scratch

COPY --from=build /app/me-snor3-parser /app/me-snor3-parser

CMD [ "/app/me-snor3-parser", "-b" ]
